version: '3'

services:
  txtdot:
    image: ghcr.io/txtdot/txtdot:latest
    ports:
      - '8088:8080'
    restart: unless-stopped
    platform: linux/arm64/v8
    volumes:
      - '.env:/app/.env'
